using DbDelta.Core.Dependency;
using DbDelta.Core.Diff;
using DbDelta.Core.ObjectModel;
using DbDelta.Core.ScriptGen;
using FluentAssertions;
using Xunit;

namespace DbDelta.Core.UnitTests.ScriptGen;

public class DeployScriptBuilderTests
{
    private static DifferencePair MakeTablePair(string schema, string name, DifferenceStatus status)
    {
        Table table = new(schema, name, [new Column("Id", "int", false, 1)]);
        return new DifferencePair(
            Identity: table.Identity,
            Status: status,
            SideA: status == DifferenceStatus.OnlyInB ? null : table,
            SideB: status == DifferenceStatus.OnlyInA ? null : table);
    }

    /// <summary>
    /// The degenerate case where the user selected everything the comparison
    /// found, i.e. full result == selection. Tests that care about the gap
    /// between the two call <see cref="DeployScriptBuilder.Build"/> directly.
    /// </summary>
    private static string BuildAllSelected(
        IReadOnlyList<DifferencePair> selected,
        string sourceSummary,
        string targetSummary,
        DateTime nowUtc) =>
        DeployScriptBuilder.Build(
            new ComparisonResult(selected), selected, sourceSummary, targetSummary, nowUtc, [], []);

    [Fact]
    public void Build_empty_selection_returns_header_only_script()
    {
        string script = BuildAllSelected(
            [],
            "SrcServer/SrcDb",
            "TgtServer/TgtDb",
            new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc));

        script.Should().Contain("-- DbDelta alignment script");
        script.Should().Contain("Objects   : 0");
        // No GO / BEGIN TRANSACTION when nothing to do.
        script.Should().NotContain("BEGIN TRANSACTION");
    }

    [Fact]
    public void Build_includes_source_and_target_summary_lines()
    {
        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T1", DifferenceStatus.OnlyInA)],
            "MYSERVER/MyDB",
            "TARGETSERVER/ProdDB",
            DateTime.UtcNow);

        script.Should().Contain("Source    : MYSERVER/MyDB");
        script.Should().Contain("Target    : TARGETSERVER/ProdDB");
    }

    [Fact]
    public void Build_uses_provided_utc_timestamp_in_header()
    {
        DateTime ts = new(2025, 6, 15, 9, 30, 0, DateTimeKind.Utc);

        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            ts);

        script.Should().Contain("2025-06-15 09:30:00 UTC");
    }

    /// <summary>
    /// The values the backfill dialog collects have to survive the app's own
    /// entry point, not just the generator's. Both buttons — «Genera script» and
    /// «Allinea destinazione» — build their script through here, so a map
    /// dropped at this seam is a deploy that dies on the first populated table
    /// with the operator's answer already given.
    /// </summary>
    [Fact]
    public void Build_passes_the_operator_supplied_backfill_values_through()
    {
        Table target = new("dbo", "TipiDoc", [new Column("Id", "int", false, 1)]);
        Table source = new("dbo", "TipiDoc",
            [new Column("Id", "int", false, 1), new Column("Corriere", "nvarchar(16)", false, 2)]);
        DifferencePair pair = new(source.Identity, DifferenceStatus.Different, source, target);

        string script = DeployScriptBuilder.Build(
            new ComparisonResult([pair]),
            [pair],
            "src",
            "tgt",
            DateTime.UtcNow,
            [],
            [],
            new Dictionary<(string, string, string), string>
            {
                [("dbo", "TipiDoc", "Corriere")] = "('GLS')",
            });

        script.Should().Contain("DEFAULT ('GLS')");
        script.Should().Contain("DROP CONSTRAINT [DF__dbdelta_backfill__Corriere];");
    }

    [Fact]
    public void Build_emits_full_verbose_envelope_without_orphan_GO()
    {
        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            DateTime.UtcNow);

        // The app's deploy path must emit the SAME self-contained verbose
        // envelope the CLI emits (v0.17.0). Regression: TrimGeneratorHeader
        // stripped the first real SET line, dropping NUMERIC_ROUNDABORT and
        // orphaning its trailing GO right under the descriptive header.
        script.Should().Contain("SET NUMERIC_ROUNDABORT OFF");
        script.Should().Contain("SET XACT_ABORT ON");
        script.Should().Contain("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");

        // Our descriptive comment header replaces the generator's bare
        // "-- Generated by DbDelta" line — it must not survive.
        script.Should().NotContain("-- Generated by DbDelta");

        // The descriptive comment header must be followed by a real SET
        // statement, never a bare GO batch separator.
        string[] lines = script.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n', StringSplitOptions.RemoveEmptyEntries);
        int firstAfterHeader = Array.FindIndex(lines, l => !l.StartsWith("--", StringComparison.Ordinal));
        lines[firstAfterHeader].Trim().Should().NotBe("GO",
            "the verbose preamble must start with a statement, not an orphaned GO");
    }

    [Fact]
    public void Build_orders_tables_before_indexes_before_fks_before_modules_before_triggers()
    {
        // Create a table (OnlyInA) which triggers table + index + FK DDL.
        Column col = new("Id", "int", false, 1);
        Table tableWithIndex = new("dbo", "Orders",
            [col],
            [new PrimaryKey("PK_Orders", ["Id"], true)],
            [new TableIndex("IX_Orders_Id", false, false, null,
                [new IndexColumn("Id", false)], [])]);

        DifferencePair tablePair = new(
            tableWithIndex.Identity,
            DifferenceStatus.OnlyInA,
            tableWithIndex,
            null);

        string script = BuildAllSelected(
            [tablePair],
            "src",
            "tgt",
            DateTime.UtcNow);

        // CREATE TABLE should appear before any index.
        int tablePos = script.IndexOf("CREATE TABLE", StringComparison.Ordinal);
        tablePos.Should().BeGreaterThan(0, "CREATE TABLE DDL must be present");

        // BEGIN TRANSACTION wraps the body.
        script.Should().Contain("BEGIN TRANSACTION");
        script.Should().Contain("COMMIT TRANSACTION");
    }

    // ── Header must never carry a secret ───────────────────────────────────

    [Fact]
    public void Build_marks_the_script_as_managing_its_own_transaction()
    {
        // `dbdelta apply` decides whether to add a client transaction of its own,
        // and getting it wrong either half-migrates the target or gives
        // @@TRANCOUNT = 2. The app suppresses the generator's comment header, so
        // the marker has to survive DoNotOutputCommentHeader — this is the path
        // that writes the .sql file a user later feeds to `apply`.
        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            DateTime.UtcNow);

        script.Should().Contain("-- dbdelta:transaction=script");
        script.Should().Contain("BEGIN TRANSACTION", "the marker must describe what the script does");
    }

    [Fact]
    public void Build_header_never_leaks_a_password_from_a_connection_string()
    {
        // Both app call sites pass live connection strings, and this header is
        // written to a .sql file that gets mailed around and committed.
        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "Server=DEV01;Database=App;Encrypt=False;TrustServerCertificate=True;User Id=sa;Password=Dev!Secret",
            "Server=PROD01;Database=App;User ID=sa;PWD=Pr0d!Secret",
            DateTime.UtcNow);

        script.Should().NotContain("Dev!Secret");
        script.Should().NotContain("Pr0d!Secret");
        script.Should().NotContain("Password=");
        script.Should().NotContain("PWD=");
        script.Should().NotContain("User Id=");
        script.Should().NotContain("User ID=");
        // Server + database survive, because that is what the header is for.
        script.Should().Contain("Source    : DEV01 / App");
        script.Should().Contain("Target    : PROD01 / App");
    }

    [Fact]
    public void Build_header_never_prints_a_quoted_password_as_the_server_name()
    {
        // A connection-string value may legally contain a semicolon when
        // quoted. Splitting on ';' by hand turned this into the tokens
        // `Password="a` and `Server=hunter2"`, so the allow-list happily
        // accepted half the password AS the server name and printed it into a
        // file people mail around. Unreachable from the setup dialog, reachable
        // from the raw connection-string box.
        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "Password=\"a;Server=hunter2\";Data Source=REAL01;Initial Catalog=App",
            "tgt",
            DateTime.UtcNow);

        script.Should().NotContain("hunter2");
        script.Should().Contain("Source    : REAL01 / App",
            "the real keys must still be found once the string is parsed properly");
    }

    [Fact]
    public void Build_header_passes_through_a_plain_label_unchanged()
    {
        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "MYSERVER/MyDB",
            "TARGETSERVER/ProdDB",
            DateTime.UtcNow);

        script.Should().Contain("Source    : MYSERVER/MyDB");
        script.Should().Contain("Target    : TARGETSERVER/ProdDB");
    }

    // ── A selected Permission row must actually be deployed ────────────────

    [Fact]
    public void Build_emits_permission_ddl_when_a_permission_row_is_selected()
    {
        // IgnorePermissions ships inside ComparisonOptions.Default, but the
        // engine still REPORTS Permission differences, so the grid offers them
        // for selection. Leaving the flag on made the generator drop them
        // silently: the script ran, said "succeeded", and the difference was
        // still there on the next compare. The selection IS the intent.
        Permission p = new("app_writer", "EXECUTE", PermissionState.Grant,
            "OBJECT_OR_COLUMN", "dbo", "uspChiudiPeriodo", null);
        DifferencePair pair = new(p.Identity, DifferenceStatus.OnlyInA, p, null);

        string script = BuildAllSelected(
            [pair], "src", "tgt", DateTime.UtcNow);

        script.Should().Contain("GRANT EXECUTE ON [dbo].[uspChiudiPeriodo] TO [app_writer];");
    }

    [Fact]
    public void Build_orders_by_dependency_edges_when_they_are_supplied()
    {
        // Without edges the topological sort degenerates to kind-then-alphabetical
        // order: View(rank 4) before Function(rank 5), so a new view that selects
        // from a new function emits first and the deploy dies on Msg 208. The app
        // used to call Build without ever passing the edges it had in hand.
        View view = new("dbo", "vFattureIva", "CREATE VIEW dbo.vFattureIva AS SELECT dbo.fnIva(1) AS x", false);
        Function fn = new("dbo", "fnIva", "CREATE FUNCTION dbo.fnIva(@v int) RETURNS int AS BEGIN RETURN @v END",
            false, FunctionKind.Scalar);
        DifferencePair viewPair = new(view.Identity, DifferenceStatus.OnlyInA, view, null);
        DifferencePair fnPair = new(fn.Identity, DifferenceStatus.OnlyInA, fn, null);

        // The view depends on the function, so the function must emit first.
        DependencyEdge edge = new(view.Identity, fn.Identity, EdgeKind.ModuleReference);

        DifferencePair[] selected = [viewPair, fnPair];
        string withEdges = DeployScriptBuilder.Build(
            new ComparisonResult(selected), selected, "src", "tgt", DateTime.UtcNow, [edge], []);

        int fnPos = withEdges.IndexOf("fnIva", StringComparison.Ordinal);
        int viewPos = withEdges.IndexOf("vFattureIva", StringComparison.Ordinal);
        fnPos.Should().BeGreaterThan(0);
        viewPos.Should().BeGreaterThan(fnPos, "the function the view selects from must be created first");
    }

    // ── The selection is not the comparison ────────────────────────────────
    //    Build used to wrap the selection in `new ComparisonResult(selectedPairs)`
    //    and pass `selection: null`, so inside Generate the full result WAS the
    //    selection. Every rescue pass that scans the unfiltered result for
    //    objects the user cannot tick — Identical rows have no checkbox
    //    (DifferenceRowViewModel.IsSelectable => !IsIdentical) — was therefore a
    //    no-op on the app path, the only path that runs against a live database.
    //    Both tests below pass an Identical pair in the full result and NOT in
    //    the selection: the shape the GUI actually produces.

    [Fact]
    public void Build_recreates_an_identical_trigger_when_only_its_rebuilt_table_is_selected()
    {
        // Target: dbo.Fatture + a byte-identical audit trigger. Source adds
        // IDENTITY to Id => full rebuild => DROP TABLE takes the trigger with
        // it. The user can only tick the Fatture row.
        static Table Fatture(bool identity)
        {
            return new Table("dbo", "Fatture",
                [new Column("Id", "int", isNullable: false, ordinal: 1,
                    isIdentity: identity, identitySeed: identity ? 1 : null,
                    identityIncrement: identity ? 1 : null)],
                [new PrimaryKey("PK_Fatture", ["Id"], IsClustered: true)],
                []);
        }
        Trigger audit = new(
            Schema: "dbo",
            Name: "trg_Fatture_Audit",
            Body: "CREATE TRIGGER dbo.trg_Fatture_Audit ON dbo.Fatture AFTER INSERT AS BEGIN SET NOCOUNT ON; END",
            IsEncrypted: false,
            ParentSchema: "dbo",
            ParentTable: "Fatture",
            IsDisabled: false,
            IsNotForReplication: false);

        DifferencePair tablePair = new(
            Fatture(true).Identity, DifferenceStatus.Different, Fatture(true), Fatture(false));
        DifferencePair triggerPair = new(
            audit.Identity, DifferenceStatus.Identical, audit, audit);

        string script = DeployScriptBuilder.Build(
            new ComparisonResult([tablePair, triggerPair]),
            [tablePair],
            "src",
            "tgt",
            DateTime.UtcNow,
            [],
            []);

        int renameIdx = script.IndexOf("sp_rename", StringComparison.Ordinal);
        int triggerIdx = script.IndexOf("TRIGGER dbo.trg_Fatture_Audit", StringComparison.Ordinal);
        renameIdx.Should().BeGreaterThan(0, "this is the rebuild path");
        triggerIdx.Should().BeGreaterThan(renameIdx,
            "DROP TABLE destroyed the trigger, so it must be re-created after the rename");
    }

    [Fact]
    public void Build_drops_an_fk_held_by_an_identical_table_when_only_the_referenced_table_is_selected()
    {
        // dbo.Currency was removed from the source; dbo.Invoice is Identical on
        // both sides and holds an FK pointing at it. Only Currency is tickable.
        ForeignKey fk = new(
            Name: "FK_Invoice_Currency",
            Columns: ["CurrencyId"],
            ReferencedSchema: "dbo",
            ReferencedTable: "Currency",
            ReferencedColumns: ["Id"],
            OnDelete: ReferentialAction.NoAction,
            OnUpdate: ReferentialAction.NoAction,
            IsDisabled: false,
            IsNotForReplication: false);
        Table currency = new("dbo", "Currency", [new Column("Id", "int", false, 1)]);
        Table invoice = new("dbo", "Invoice",
            [new Column("Id", "int", false, 1), new Column("CurrencyId", "int", false, 2)],
            [fk],
            []);

        DifferencePair currencyPair = new(
            currency.Identity, DifferenceStatus.OnlyInB, null, currency);
        DifferencePair invoicePair = new(
            invoice.Identity, DifferenceStatus.Identical, invoice, invoice);

        string script = DeployScriptBuilder.Build(
            new ComparisonResult([currencyPair, invoicePair]),
            [currencyPair],
            "src",
            "tgt",
            DateTime.UtcNow,
            [],
            []);

        int dropFk = script.IndexOf(
            "ALTER TABLE [dbo].[Invoice] DROP CONSTRAINT [FK_Invoice_Currency];",
            StringComparison.Ordinal);
        int dropTable = script.IndexOf("DROP TABLE [dbo].[Currency];", StringComparison.Ordinal);
        dropFk.Should().BeGreaterThan(0,
            "DROP TABLE fails with Msg 3726 while the FK on the Identical table still references it");
        dropTable.Should().BeGreaterThan(dropFk);
    }

    [Fact]
    public void Build_still_ignores_permissions_when_none_is_selected()
    {
        string script = BuildAllSelected(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            DateTime.UtcNow);

        script.Should().NotContain("GRANT");
    }
}
