using DbDelta.Core.Diff;
using DbDelta.Core.ObjectModel;
using DbDelta.Core.ScriptGen;
using FluentAssertions;
using Xunit;

namespace DbDelta.Core.UnitTests.ScriptGen;

public class DeployScriptBuilderTests
{
    private static DifferencePair MakeTablePair(string schema, string name, DifferenceStatus status)
    {
        Table table = new(schema, name, [new Column("Id", "int", false, 1)]);
        return new DifferencePair(
            Identity: table.Identity,
            Status: status,
            SideA: status == DifferenceStatus.OnlyInB ? null : table,
            SideB: status == DifferenceStatus.OnlyInA ? null : table);
    }

    [Fact]
    public void Build_empty_selection_returns_header_only_script()
    {
        string script = DeployScriptBuilder.Build(
            [],
            "SrcServer/SrcDb",
            "TgtServer/TgtDb",
            new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc));

        script.Should().Contain("-- DbDelta alignment script");
        script.Should().Contain("Objects   : 0");
        // No GO / BEGIN TRANSACTION when nothing to do.
        script.Should().NotContain("BEGIN TRANSACTION");
    }

    [Fact]
    public void Build_includes_source_and_target_summary_lines()
    {
        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T1", DifferenceStatus.OnlyInA)],
            "MYSERVER/MyDB",
            "TARGETSERVER/ProdDB",
            DateTime.UtcNow);

        script.Should().Contain("Source    : MYSERVER/MyDB");
        script.Should().Contain("Target    : TARGETSERVER/ProdDB");
    }

    [Fact]
    public void Build_uses_provided_utc_timestamp_in_header()
    {
        DateTime ts = new(2025, 6, 15, 9, 30, 0, DateTimeKind.Utc);

        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            ts);

        script.Should().Contain("2025-06-15 09:30:00 UTC");
    }

    [Fact]
    public void Build_emits_full_verbose_envelope_without_orphan_GO()
    {
        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            DateTime.UtcNow);

        // The app's deploy path must emit the SAME self-contained verbose
        // envelope the CLI emits (v0.17.0). Regression: TrimGeneratorHeader
        // stripped the first real SET line, dropping NUMERIC_ROUNDABORT and
        // orphaning its trailing GO right under the descriptive header.
        script.Should().Contain("SET NUMERIC_ROUNDABORT OFF");
        script.Should().Contain("SET XACT_ABORT ON");
        script.Should().Contain("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");

        // Our descriptive comment header replaces the generator's bare
        // "-- Generated by DbDelta" line — it must not survive.
        script.Should().NotContain("-- Generated by DbDelta");

        // The descriptive comment header must be followed by a real SET
        // statement, never a bare GO batch separator.
        string[] lines = script.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n', StringSplitOptions.RemoveEmptyEntries);
        int firstAfterHeader = Array.FindIndex(lines, l => !l.StartsWith("--", StringComparison.Ordinal));
        lines[firstAfterHeader].Trim().Should().NotBe("GO",
            "the verbose preamble must start with a statement, not an orphaned GO");
    }

    [Fact]
    public void Build_orders_tables_before_indexes_before_fks_before_modules_before_triggers()
    {
        // Create a table (OnlyInA) which triggers table + index + FK DDL.
        Column col = new("Id", "int", false, 1);
        Table tableWithIndex = new("dbo", "Orders",
            [col],
            [new PrimaryKey("PK_Orders", ["Id"], true)],
            [new TableIndex("IX_Orders_Id", false, false, null,
                [new IndexColumn("Id", false)], [])]);

        DifferencePair tablePair = new(
            tableWithIndex.Identity,
            DifferenceStatus.OnlyInA,
            tableWithIndex,
            null);

        string script = DeployScriptBuilder.Build(
            [tablePair],
            "src",
            "tgt",
            DateTime.UtcNow);

        // CREATE TABLE should appear before any index.
        int tablePos = script.IndexOf("CREATE TABLE", StringComparison.Ordinal);
        tablePos.Should().BeGreaterThan(0, "CREATE TABLE DDL must be present");

        // BEGIN TRANSACTION wraps the body.
        script.Should().Contain("BEGIN TRANSACTION");
        script.Should().Contain("COMMIT TRANSACTION");
    }
}
