using DbDelta.Core.Dependency;
using DbDelta.Core.Diff;
using DbDelta.Core.ObjectModel;
using DbDelta.Core.ScriptGen;
using FluentAssertions;
using Xunit;

namespace DbDelta.Core.UnitTests.ScriptGen;

public class DeployScriptBuilderTests
{
    private static DifferencePair MakeTablePair(string schema, string name, DifferenceStatus status)
    {
        Table table = new(schema, name, [new Column("Id", "int", false, 1)]);
        return new DifferencePair(
            Identity: table.Identity,
            Status: status,
            SideA: status == DifferenceStatus.OnlyInB ? null : table,
            SideB: status == DifferenceStatus.OnlyInA ? null : table);
    }

    [Fact]
    public void Build_empty_selection_returns_header_only_script()
    {
        string script = DeployScriptBuilder.Build(
            [],
            "SrcServer/SrcDb",
            "TgtServer/TgtDb",
            new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc));

        script.Should().Contain("-- DbDelta alignment script");
        script.Should().Contain("Objects   : 0");
        // No GO / BEGIN TRANSACTION when nothing to do.
        script.Should().NotContain("BEGIN TRANSACTION");
    }

    [Fact]
    public void Build_includes_source_and_target_summary_lines()
    {
        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T1", DifferenceStatus.OnlyInA)],
            "MYSERVER/MyDB",
            "TARGETSERVER/ProdDB",
            DateTime.UtcNow);

        script.Should().Contain("Source    : MYSERVER/MyDB");
        script.Should().Contain("Target    : TARGETSERVER/ProdDB");
    }

    [Fact]
    public void Build_uses_provided_utc_timestamp_in_header()
    {
        DateTime ts = new(2025, 6, 15, 9, 30, 0, DateTimeKind.Utc);

        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            ts);

        script.Should().Contain("2025-06-15 09:30:00 UTC");
    }

    [Fact]
    public void Build_emits_full_verbose_envelope_without_orphan_GO()
    {
        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            DateTime.UtcNow);

        // The app's deploy path must emit the SAME self-contained verbose
        // envelope the CLI emits (v0.17.0). Regression: TrimGeneratorHeader
        // stripped the first real SET line, dropping NUMERIC_ROUNDABORT and
        // orphaning its trailing GO right under the descriptive header.
        script.Should().Contain("SET NUMERIC_ROUNDABORT OFF");
        script.Should().Contain("SET XACT_ABORT ON");
        script.Should().Contain("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");

        // Our descriptive comment header replaces the generator's bare
        // "-- Generated by DbDelta" line — it must not survive.
        script.Should().NotContain("-- Generated by DbDelta");

        // The descriptive comment header must be followed by a real SET
        // statement, never a bare GO batch separator.
        string[] lines = script.Replace("\r\n", "\n", StringComparison.Ordinal)
            .Split('\n', StringSplitOptions.RemoveEmptyEntries);
        int firstAfterHeader = Array.FindIndex(lines, l => !l.StartsWith("--", StringComparison.Ordinal));
        lines[firstAfterHeader].Trim().Should().NotBe("GO",
            "the verbose preamble must start with a statement, not an orphaned GO");
    }

    [Fact]
    public void Build_orders_tables_before_indexes_before_fks_before_modules_before_triggers()
    {
        // Create a table (OnlyInA) which triggers table + index + FK DDL.
        Column col = new("Id", "int", false, 1);
        Table tableWithIndex = new("dbo", "Orders",
            [col],
            [new PrimaryKey("PK_Orders", ["Id"], true)],
            [new TableIndex("IX_Orders_Id", false, false, null,
                [new IndexColumn("Id", false)], [])]);

        DifferencePair tablePair = new(
            tableWithIndex.Identity,
            DifferenceStatus.OnlyInA,
            tableWithIndex,
            null);

        string script = DeployScriptBuilder.Build(
            [tablePair],
            "src",
            "tgt",
            DateTime.UtcNow);

        // CREATE TABLE should appear before any index.
        int tablePos = script.IndexOf("CREATE TABLE", StringComparison.Ordinal);
        tablePos.Should().BeGreaterThan(0, "CREATE TABLE DDL must be present");

        // BEGIN TRANSACTION wraps the body.
        script.Should().Contain("BEGIN TRANSACTION");
        script.Should().Contain("COMMIT TRANSACTION");
    }

    // ── Header must never carry a secret ───────────────────────────────────

    [Fact]
    public void Build_header_never_leaks_a_password_from_a_connection_string()
    {
        // Both app call sites pass live connection strings, and this header is
        // written to a .sql file that gets mailed around and committed.
        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "Server=DEV01;Database=App;Encrypt=False;TrustServerCertificate=True;User Id=sa;Password=Dev!Secret",
            "Server=PROD01;Database=App;User ID=sa;PWD=Pr0d!Secret",
            DateTime.UtcNow);

        script.Should().NotContain("Dev!Secret");
        script.Should().NotContain("Pr0d!Secret");
        script.Should().NotContain("Password=");
        script.Should().NotContain("PWD=");
        script.Should().NotContain("User Id=");
        script.Should().NotContain("User ID=");
        // Server + database survive, because that is what the header is for.
        script.Should().Contain("Source    : DEV01 / App");
        script.Should().Contain("Target    : PROD01 / App");
    }

    [Fact]
    public void Build_header_passes_through_a_plain_label_unchanged()
    {
        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "MYSERVER/MyDB",
            "TARGETSERVER/ProdDB",
            DateTime.UtcNow);

        script.Should().Contain("Source    : MYSERVER/MyDB");
        script.Should().Contain("Target    : TARGETSERVER/ProdDB");
    }

    // ── A selected Permission row must actually be deployed ────────────────

    [Fact]
    public void Build_emits_permission_ddl_when_a_permission_row_is_selected()
    {
        // IgnorePermissions ships inside ComparisonOptions.Default, but the
        // engine still REPORTS Permission differences, so the grid offers them
        // for selection. Leaving the flag on made the generator drop them
        // silently: the script ran, said "succeeded", and the difference was
        // still there on the next compare. The selection IS the intent.
        Permission p = new("app_writer", "EXECUTE", PermissionState.Grant,
            "OBJECT_OR_COLUMN", "dbo", "uspChiudiPeriodo", null);
        DifferencePair pair = new(p.Identity, DifferenceStatus.OnlyInA, p, null);

        string script = DeployScriptBuilder.Build(
            [pair], "src", "tgt", DateTime.UtcNow);

        script.Should().Contain("GRANT EXECUTE ON [dbo].[uspChiudiPeriodo] TO [app_writer];");
    }

    [Fact]
    public void Build_orders_by_dependency_edges_when_they_are_supplied()
    {
        // Without edges the topological sort degenerates to kind-then-alphabetical
        // order: View(rank 4) before Function(rank 5), so a new view that selects
        // from a new function emits first and the deploy dies on Msg 208. The app
        // used to call Build without ever passing the edges it had in hand.
        View view = new("dbo", "vFattureIva", "CREATE VIEW dbo.vFattureIva AS SELECT dbo.fnIva(1) AS x", false);
        Function fn = new("dbo", "fnIva", "CREATE FUNCTION dbo.fnIva(@v int) RETURNS int AS BEGIN RETURN @v END",
            false, FunctionKind.Scalar);
        DifferencePair viewPair = new(view.Identity, DifferenceStatus.OnlyInA, view, null);
        DifferencePair fnPair = new(fn.Identity, DifferenceStatus.OnlyInA, fn, null);

        // The view depends on the function, so the function must emit first.
        DependencyEdge edge = new(view.Identity, fn.Identity, EdgeKind.ModuleReference);

        string withEdges = DeployScriptBuilder.Build(
            [viewPair, fnPair], "src", "tgt", DateTime.UtcNow, [edge]);

        int fnPos = withEdges.IndexOf("fnIva", StringComparison.Ordinal);
        int viewPos = withEdges.IndexOf("vFattureIva", StringComparison.Ordinal);
        fnPos.Should().BeGreaterThan(0);
        viewPos.Should().BeGreaterThan(fnPos, "the function the view selects from must be created first");
    }

    [Fact]
    public void Build_still_ignores_permissions_when_none_is_selected()
    {
        string script = DeployScriptBuilder.Build(
            [MakeTablePair("dbo", "T", DifferenceStatus.OnlyInA)],
            "src",
            "tgt",
            DateTime.UtcNow);

        script.Should().NotContain("GRANT");
    }
}
