using System.Text;
using DbDelta.Core.Diff;
using DbDelta.Core.ObjectModel;
using DbDelta.Core.Options;
using DbDelta.Core.ScriptGen;
using FluentAssertions;
using Xunit;

namespace DbDelta.Core.UnitTests.ScriptGen;

public class DeploymentScriptWriterTests
{
    private static string Render(Action<DeploymentScriptWriter> act)
    {
        StringBuilder sb = new();
        act(new DeploymentScriptWriter(sb, useTransaction: true));
        return sb.ToString();
    }

    [Fact]
    public void WriteBatch_frames_label_body_and_error_gate()
    {
        string s = Render(w => w.WriteBatch("Creating [dbo].[X]", "CREATE TABLE [dbo].[X] (Id int);"));
        s.Should().Contain("PRINT N'Creating [dbo].[X]';");
        s.Should().Contain("CREATE TABLE [dbo].[X] (Id int);");
        s.Should().Contain("IF @@ERROR <> 0 SET NOEXEC ON;");
        s.IndexOf("PRINT N'Creating", StringComparison.Ordinal)
            .Should().BeLessThan(s.IndexOf("CREATE TABLE", StringComparison.Ordinal));
        s.IndexOf("CREATE TABLE", StringComparison.Ordinal)
            .Should().BeLessThan(s.IndexOf("IF @@ERROR", StringComparison.Ordinal));
    }

    [Fact]
    public void WriteBatch_doubles_single_quotes_in_the_label()
    {
        string s = Render(w => w.WriteBatch("Creating [dbo].[O'Brien]", "x"));
        s.Should().Contain("PRINT N'Creating [dbo].[O''Brien]';");
    }

    [Fact]
    public void WriteBatch_skips_empty_body() => Render(w => w.WriteBatch("noop", "   ")).Should().BeEmpty();

    [Fact]
    public void Preamble_with_transaction_emits_sets_and_begin()
    {
        string s = Render(w => w.WritePreamble(includeHeader: true));
        s.Should().Contain("-- Generated by DbDelta");
        s.Should().Contain("SET XACT_ABORT ON");
        s.Should().Contain("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
        s.Should().Contain("BEGIN TRANSACTION");
    }

    [Fact]
    public void Verdict_with_transaction_commits_and_reports_success_or_rollback()
    {
        string s = Render(w => w.WriteVerdict());
        s.Should().Contain("COMMIT TRANSACTION");
        s.Should().Contain("SET NOEXEC OFF");
        s.Should().Contain("PRINT 'The database update succeeded'");
        s.Should().Contain("IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION");
        s.Should().Contain("PRINT 'The database update failed'");
    }

    [Fact]
    public void No_transaction_mode_omits_begin_and_commit()
    {
        StringBuilder sb = new();
        DeploymentScriptWriter w = new(sb, useTransaction: false);
        w.WritePreamble(includeHeader: false);
        w.WriteVerdict();
        string s = sb.ToString();
        s.Should().NotContain("BEGIN TRANSACTION");
        s.Should().NotContain("COMMIT TRANSACTION");
        s.Should().Contain("SET NOEXEC OFF");
        // Omitting the envelope is not the same as saying so. Without this line
        // the script was indistinguishable from a hand-written one and `apply`
        // wrapped it in a client transaction, undoing the option that generated
        // it. Spelled literally: it is a wire format other versions have to read.
        s.Should().StartWith("-- dbdelta:transaction=none");
        s.Should().NotContain("-- dbdelta:transaction=script");
    }
    /// <summary>
    /// The wiring, not the writer: that `ComparisonOptions.NoTransactions`
    /// actually reaches `useTransaction: false` and comes out as the marker
    /// `apply` reads. Nothing else covers it — no CLI option and no GUI control
    /// sets that flag today, so without this test the whole `=none` branch could
    /// be deleted and every other test would stay green.
    /// </summary>
    [Fact]
    public void NoTransactions_reaches_the_writer_and_comes_out_as_the_marker()
    {
        Table t = new("dbo", "T", [new Column("Id", "int", false, 1)], [], []);
        Database src = new("Db", Schemas: [new Schema("dbo")], Tables: [t], Views: [], Procedures: []);
        Database tgt = new("Db", Schemas: [new Schema("dbo")], Tables: [], Views: [], Procedures: []);
        ComparisonResult result = new ComparisonEngine().Compare(src, tgt, ComparisonOptions.Default);

        string script = new ScriptGenerator().Generate(
            result, options: ComparisonOptions.Default | ComparisonOptions.NoTransactions);

        // First line, because that is where the reader looks: a marker further
        // down would not count, on purpose.
        script.Should().StartWith("-- dbdelta:transaction=none");
        script.Should().NotContain("BEGIN TRANSACTION", "the marker must describe what the script does");
        script.Should().Contain("CREATE TABLE", "and it still has to be a deploy script");
    }
}
