<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Meziantou.Framework.Win32.CredentialManager" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DbDelta.Core\DbDelta.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="DbDelta.Persistence.IntegrationTests" />
  </ItemGroup>
</Project>
