using System.Text;
using DbDelta.Core.Diff;

namespace DbDelta.Core.ScriptGen;

/// <summary>
/// Composes a deployment-ready T-SQL script for a user-selected subset of
/// <see cref="DifferencePair"/> objects. The generated script includes a
/// descriptive header (timestamp, source / target endpoints) followed by the
/// DDL body produced by the topologically ordered emitter pipeline already
/// implemented in <see cref="ScriptGenerator"/>.
/// </summary>
public static class DeployScriptBuilder
{
    private static readonly ScriptGenerator _generator = new();

    /// <summary>
    /// Builds the alignment script for <paramref name="selectedPairs"/>.
    /// </summary>
    /// <param name="selectedPairs">The pairs selected by the user in the grid.</param>
    /// <param name="sourceEndpointSummary">Human-readable label for the source endpoint (server+db).</param>
    /// <param name="targetEndpointSummary">Human-readable label for the target endpoint (server+db).</param>
    /// <param name="nowUtc">The UTC timestamp to embed in the header.</param>
    /// <param name="targetDefaultCollation">
    /// Default collation of the target database — used to skip redundant
    /// <c>COLLATE</c> clauses on string columns whose collation matches the
    /// default (M13-PARITY.5 #32). Pass <c>null</c> when unknown.
    /// </param>
    public static string Build(
        IReadOnlyList<DifferencePair> selectedPairs,
        string sourceEndpointSummary,
        string targetEndpointSummary,
        DateTime nowUtc,
        string? targetDefaultCollation = null)
    {
        ArgumentNullException.ThrowIfNull(selectedPairs);

        StringBuilder header = new();
        header.AppendLine("-- ============================================================");
        header.AppendLine($"-- DbDelta alignment script");
        header.AppendLine($"-- Generated : {nowUtc:yyyy-MM-dd HH:mm:ss} UTC");
        header.AppendLine($"-- Source    : {sourceEndpointSummary}");
        header.AppendLine($"-- Target    : {targetEndpointSummary}");
        header.AppendLine($"-- Objects   : {selectedPairs.Count}");
        header.AppendLine("-- ============================================================");
        header.AppendLine("SET XACT_ABORT ON;");

        if (selectedPairs.Count == 0)
        {
            return header.ToString();
        }

        // Wrap the selection in a synthetic ComparisonResult so the existing
        // ScriptGenerator pipeline (with its topological ordering) can be reused.
        // ScriptGenerator.Generate already prepends its own minimal header and
        // wraps in BEGIN/COMMIT TRANSACTION; we strip the first two header lines
        // it adds and keep everything else so the ordering logic is preserved.
        ComparisonResult syntheticResult = new(selectedPairs);
        string body = _generator.Generate(
            syntheticResult,
            selection: null,
            options: Core.Options.ComparisonOptions.Default,
            targetDefaultCollation: targetDefaultCollation);

        // The body already starts with "-- Generated by DbDelta\nSET XACT_ABORT ON;\n..."
        // Remove that short header (2 lines) and replace it with ours.
        string trimmedBody = TrimGeneratorHeader(body);

        return header.ToString() + trimmedBody;
    }

    /// <summary>
    /// Removes the two-line header that <see cref="ScriptGenerator.Generate"/>
    /// prepends so the caller-supplied header can replace it without duplication.
    /// </summary>
    private static string TrimGeneratorHeader(string body)
    {
        // The generator emits exactly:
        //   "-- Generated by DbDelta\r?\n"
        //   "SET XACT_ABORT ON;\r?\n"
        // Strip those two lines; return the remainder as-is.
        ReadOnlySpan<char> span = body.AsSpan();
        int linesSkipped = 0;
        int pos = 0;
        while (pos < span.Length && linesSkipped < 2)
        {
            int nl = span[pos..].IndexOf('\n');
            if (nl < 0)
            {
                break;
            }
            pos += nl + 1;
            linesSkipped++;
        }
        return linesSkipped == 2 ? body[pos..] : body;
    }
}
