using System.Text;

namespace DbDelta.Core.ScriptGen;

/// <summary>
/// Emits a self-contained, Redgate-style deployment script: a SET preamble +
/// BEGIN TRANSACTION, each operation wrapped as a PRINT phase label + body + an
/// <c>IF @@ERROR &lt;&gt; 0 SET NOEXEC ON</c> gate, and a final succeeded/failed
/// verdict that rolls back on failure. With <paramref name="useTransaction"/>
/// false the BEGIN/COMMIT are omitted (the verdict still rolls back any open
/// transaction).
/// </summary>
public sealed class DeploymentScriptWriter(StringBuilder sb, bool useTransaction)
{
    /// <summary>
    /// Marker that declares, by provenance rather than by syntax, that this
    /// script opens and closes its own transaction. <c>dbdelta apply</c> reads
    /// it to decide whether to add a client transaction of its own: the two
    /// modes are mutually exclusive (a client transaction on top gives
    /// <c>@@TRANCOUNT = 2</c>, so the script's COMMIT becomes a bare decrement).
    /// Emitted regardless of <c>includeHeader</c> — the app suppresses the
    /// human-readable header but its saved script still has to be classifiable.
    /// </summary>
    public const string SelfManagedTransactionMarker = "-- dbdelta:transaction=script";

    public void WritePreamble(bool includeHeader)
    {
        if (useTransaction) { sb.AppendLine(SelfManagedTransactionMarker); }
        if (includeHeader) { sb.AppendLine("-- Generated by DbDelta"); }
        Batch("SET NUMERIC_ROUNDABORT OFF");
        Batch("SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON");
        Batch("SET XACT_ABORT ON");
        Batch("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
        if (useTransaction)
        {
            Batch("BEGIN TRANSACTION");
            Batch("IF @@ERROR <> 0 SET NOEXEC ON");
        }
    }

    public void WriteBatch(string label, string body)
    {
        ArgumentNullException.ThrowIfNull(label);
        ArgumentNullException.ThrowIfNull(body);
        if (string.IsNullOrWhiteSpace(body)) { return; }
        sb.Append("PRINT N'").Append(label.Replace("'", "''", StringComparison.Ordinal)).AppendLine("';");
        sb.AppendLine("GO");
        sb.AppendLine(body.TrimEnd());
        sb.AppendLine("GO");
        sb.AppendLine("IF @@ERROR <> 0 SET NOEXEC ON;");
        sb.AppendLine("GO");
    }

    public void WriteVerdict()
    {
        if (useTransaction)
        {
            Batch("COMMIT TRANSACTION");
            Batch("IF @@ERROR <> 0 SET NOEXEC ON");
        }
        // DECLARE compiles even under NOEXEC (the variable exists); SET is skipped
        // on error, leaving @Success NULL → the ELSE branch rolls back + reports failure.
        sb.AppendLine("DECLARE @Success AS BIT");
        sb.AppendLine("SET @Success = 1");
        sb.AppendLine("SET NOEXEC OFF");
        sb.AppendLine("IF (@Success = 1) PRINT 'The database update succeeded'");
        sb.AppendLine("ELSE BEGIN");
        sb.AppendLine("    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION");
        sb.AppendLine("    PRINT 'The database update failed'");
        sb.AppendLine("END");
        sb.AppendLine("GO");
    }

    private void Batch(string statement)
    {
        sb.AppendLine(statement);
        sb.AppendLine("GO");
    }
}
