using System.Text;

namespace DbDelta.Core.ScriptGen;

/// <summary>
/// Emits a self-contained, Redgate-style deployment script: a SET preamble +
/// BEGIN TRANSACTION, each operation wrapped as a PRINT phase label + body + an
/// <c>IF @@ERROR &lt;&gt; 0 SET NOEXEC ON</c> gate, and a final succeeded/failed
/// verdict that rolls back on failure. With <paramref name="useTransaction"/>
/// false the BEGIN/COMMIT are omitted (the verdict still rolls back any open
/// transaction).
/// </summary>
/// <remarks>
/// <para>
/// What that gate catches was measured on <c>mssql/server:2022-latest</c>
/// 16.0.4265.3, not assumed. <c>@@ERROR</c> survives the <c>GO</c>, so the gate
/// does read the previous batch's last statement — it is not a no-op. It is
/// blind as soon as a statement that succeeds follows the failed one in the same
/// batch, because <c>@@ERROR</c> reports the LAST statement and even a
/// <c>PRINT</c> clears it; and it is blind to <c>EXEC</c> in every position,
/// last included — a failed <c>sp_rename</c> leaves <c>@@ERROR</c> at 0 and
/// reports the failure only through a non-zero return code.
/// </para>
/// <para>
/// That is survivable, and the reason is severity rather than
/// <c>XACT_ABORT</c>. Severity 11 lets the batch continue and commit, and only
/// one thing reaches severity 11: "the object is not there" — Msg 3701 for a
/// missing table, view, procedure, function, index, sequence, synonym or
/// trigger, plus Msg 15225 and 15335 from <c>sp_rename</c>. Everything that
/// would leave the target in a shape nobody asked for is severity 14 or higher
/// and aborts the batch, taking the transaction with it: Msg 2714, 3726,
/// 3727/3728, 4902, 8106, 218, 15151, 207 — and Msg 3701 ITSELF when it means
/// "you do not have permission", which is raised at severity 14. So a swallowed
/// error can only be the second-run case that bare DROPs already declare
/// unsupported. The whole rule, including why <c>apply</c> is stricter than the
/// saved script, is "Why no DROP is guarded" in <c>docfx/articles/cli.md</c>.
/// </para>
/// </remarks>
public sealed class DeploymentScriptWriter(StringBuilder sb, bool useTransaction)
{
    /// <summary>
    /// Marker that declares, by provenance rather than by syntax, that this
    /// script opens and closes its own transaction. <c>dbdelta apply</c> reads
    /// it to decide whether to add a client transaction of its own: the two
    /// modes are mutually exclusive (a client transaction on top gives
    /// <c>@@TRANCOUNT = 2</c>, so the script's COMMIT becomes a bare decrement).
    /// Emitted regardless of <c>includeHeader</c> — the app suppresses the
    /// human-readable header but its saved script still has to be classifiable.
    /// </summary>
    public const string SelfManagedTransactionMarker = "-- dbdelta:transaction=script";

    public void WritePreamble(bool includeHeader)
    {
        if (useTransaction) { sb.AppendLine(SelfManagedTransactionMarker); }
        if (includeHeader) { sb.AppendLine("-- Generated by DbDelta"); }
        Batch("SET NUMERIC_ROUNDABORT OFF");
        Batch("SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON");
        Batch("SET XACT_ABORT ON");
        Batch("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE");
        if (useTransaction)
        {
            Batch("BEGIN TRANSACTION");
            Batch("IF @@ERROR <> 0 SET NOEXEC ON");
        }
    }

    /// <summary>
    /// Writes one phase: the label, then the body, then the failure gate.
    /// </summary>
    /// <remarks>
    /// A body may contain its own <c>GO</c> lines, and each part then becomes a
    /// separately gated batch under the one label. Emitters need that because
    /// SQL Server compiles a whole batch before running any of it: an
    /// <c>ALTER TABLE … ADD [C]</c> followed in the SAME batch by a CHECK over
    /// <c>[C]</c> fails to compile with Msg 207, since the column does not exist
    /// yet at compile time. Splitting here rather than at the call site keeps
    /// every part gated — a body spliced in raw would leave all but the last
    /// batch unguarded, so a failure in the middle would not stop the rest.
    /// </remarks>
    public void WriteBatch(string label, string body)
    {
        ArgumentNullException.ThrowIfNull(label);
        ArgumentNullException.ThrowIfNull(body);
        if (string.IsNullOrWhiteSpace(body)) { return; }
        sb.Append("PRINT N'").Append(label.Replace("'", "''", StringComparison.Ordinal)).AppendLine("';");
        sb.AppendLine("GO");
        foreach (string part in SplitOnGo(body))
        {
            sb.AppendLine(part);
            sb.AppendLine("GO");
            sb.AppendLine("IF @@ERROR <> 0 SET NOEXEC ON;");
            sb.AppendLine("GO");
        }
    }

    /// <summary>
    /// Splits a body on lines consisting solely of <c>GO</c>, dropping empty
    /// parts. A body with no separator comes back as a single part, so the
    /// common case is unchanged byte-for-byte.
    /// </summary>
    private static List<string> SplitOnGo(string body)
    {
        List<string> parts = [];
        List<string> current = [];
        foreach (string line in body.Split(["\r\n", "\n", "\r"], StringSplitOptions.None))
        {
            if (line.Trim().Equals("GO", StringComparison.OrdinalIgnoreCase))
            {
                Flush(parts, current);
                continue;
            }
            current.Add(line);
        }
        Flush(parts, current);
        return parts;

        static void Flush(List<string> parts, List<string> current)
        {
            string part = string.Join(Environment.NewLine, current).TrimEnd();
            if (!string.IsNullOrWhiteSpace(part)) { parts.Add(part); }
            current.Clear();
        }
    }

    public void WriteVerdict()
    {
        if (useTransaction)
        {
            Batch("COMMIT TRANSACTION");
            Batch("IF @@ERROR <> 0 SET NOEXEC ON");
        }
        // DECLARE compiles even under NOEXEC (the variable exists); SET is skipped
        // on error, leaving @Success NULL → the ELSE branch rolls back + reports failure.
        sb.AppendLine("DECLARE @Success AS BIT");
        sb.AppendLine("SET @Success = 1");
        sb.AppendLine("SET NOEXEC OFF");
        sb.AppendLine("IF (@Success = 1) PRINT 'The database update succeeded'");
        sb.AppendLine("ELSE BEGIN");
        sb.AppendLine("    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION");
        sb.AppendLine("    PRINT 'The database update failed'");
        sb.AppendLine("END");
        sb.AppendLine("GO");
    }

    private void Batch(string statement)
    {
        sb.AppendLine(statement);
        sb.AppendLine("GO");
    }
}
