using System.Text;
using DbDelta.Core.Diff;

namespace DbDelta.Core.ScriptGen;

/// <summary>
/// Composes a deployment-ready T-SQL script for a user-selected subset of
/// <see cref="DifferencePair"/> objects. The generated script includes a
/// descriptive header (timestamp, source / target endpoints) followed by the
/// DDL body produced by the topologically ordered emitter pipeline already
/// implemented in <see cref="ScriptGenerator"/>.
/// </summary>
public static class DeployScriptBuilder
{
    private static readonly ScriptGenerator _generator = new();

    /// <summary>
    /// Builds the alignment script for <paramref name="selectedPairs"/>.
    /// </summary>
    /// <param name="selectedPairs">The pairs selected by the user in the grid.</param>
    /// <param name="sourceEndpointSummary">Human-readable label for the source endpoint (server+db).</param>
    /// <param name="targetEndpointSummary">Human-readable label for the target endpoint (server+db).</param>
    /// <param name="nowUtc">The UTC timestamp to embed in the header.</param>
    public static string Build(
        IReadOnlyList<DifferencePair> selectedPairs,
        string sourceEndpointSummary,
        string targetEndpointSummary,
        DateTime nowUtc)
    {
        ArgumentNullException.ThrowIfNull(selectedPairs);

        StringBuilder header = new();
        header.AppendLine("-- ============================================================");
        header.AppendLine($"-- DbDelta alignment script");
        header.AppendLine($"-- Generated : {nowUtc:yyyy-MM-dd HH:mm:ss} UTC");
        header.AppendLine($"-- Source    : {sourceEndpointSummary}");
        header.AppendLine($"-- Target    : {targetEndpointSummary}");
        header.AppendLine($"-- Objects   : {selectedPairs.Count}");
        header.AppendLine("-- ============================================================");

        if (selectedPairs.Count == 0)
        {
            return header.ToString();
        }

        // Wrap the selection in a synthetic ComparisonResult so the existing
        // ScriptGenerator pipeline (topological ordering + the self-contained
        // verbose deployment envelope) can be reused verbatim. We suppress the
        // generator's bare "-- Generated by DbDelta" line via
        // DoNotOutputCommentHeader so our descriptive header stands alone — no
        // trimming, no orphaned GO. Keep the Redgate-parity defaults.
        ComparisonResult syntheticResult = new(selectedPairs);
        string body = _generator.Generate(
            syntheticResult,
            selection: null,
            options: Options.ComparisonOptions.Default | Options.ComparisonOptions.DoNotOutputCommentHeader);

        return header.ToString() + body;
    }
}
