using System.Text;
using DbDelta.Core.Diff;
using DbDelta.Core.ObjectModel;

namespace DbDelta.Core.ScriptGen;

/// <summary>
/// Orchestrates per-object emitters and wraps the output in a deployment-ready
/// batch. Order: tables (with PK/UQ/CK/DF/identity/computed inline) → standalone
/// CREATE INDEX → ALTER TABLE ADD CONSTRAINT … FOREIGN KEY.
/// </summary>
public sealed class ScriptGenerator
{
    private readonly TableScriptEmitter _tableEmitter = new();
    private readonly IndexScriptEmitter _indexEmitter = new();
    private readonly ForeignKeyScriptEmitter _fkEmitter = new();

    /// <summary>
    /// Generates a complete T-SQL migration script for the given comparison result.
    /// </summary>
    public string Generate(ComparisonResult result, IEnumerable<DifferencePair>? selection = null)
    {
        ArgumentNullException.ThrowIfNull(result);
        List<DifferencePair> pairs = [.. (selection ?? result.Differences)
            .Where(p => p.Status != DifferenceStatus.Identical)];

        StringBuilder sb = new();
        sb.AppendLine("-- Generated by DbDelta");
        sb.AppendLine("SET XACT_ABORT ON;");
        sb.AppendLine("BEGIN TRANSACTION;");
        sb.AppendLine("GO");

        // 1. Tables (CREATE / DROP / ALTER ADD COLUMN + ALTER ADD CONSTRAINT)
        foreach (DifferencePair pair in pairs)
        {
            string tableDdl = _tableEmitter.Emit(pair);
            if (!string.IsNullOrWhiteSpace(tableDdl))
            {
                sb.AppendLine(tableDdl);
                sb.AppendLine("GO");
            }
        }

        // 2. Indexes — emitted for newly created tables (OnlyInA).
        //    Full add/drop index diff on Different tables lands in M8.
        foreach (DifferencePair pair in pairs)
        {
            if (pair.Status != DifferenceStatus.OnlyInA || pair.SideA is not Table t)
            {
                continue;
            }
            if (t.Indexes.Count == 0)
            {
                continue;
            }
            foreach (TableIndex ix in t.Indexes)
            {
                sb.AppendLine(_indexEmitter.EmitCreate(t.Schema, t.Name, ix));
            }
            sb.AppendLine("GO");
        }

        // 3. Foreign keys — emitted last so referenced tables already exist.
        foreach (DifferencePair pair in pairs)
        {
            if (pair.Status != DifferenceStatus.OnlyInA || pair.SideA is not Table t)
            {
                continue;
            }
            List<ForeignKey> fks = [.. t.Constraints.OfType<ForeignKey>()];
            if (fks.Count == 0)
            {
                continue;
            }
            foreach (ForeignKey fk in fks)
            {
                sb.AppendLine(_fkEmitter.EmitAdd(t.Schema, t.Name, fk));
            }
            sb.AppendLine("GO");
        }

        sb.AppendLine("COMMIT TRANSACTION;");
        sb.AppendLine("GO");
        return sb.ToString();
    }
}
