using System.Text;
using DbDelta.Core.Diff;
using DbDelta.Core.ObjectModel;
using DbDelta.Core.Options;

namespace DbDelta.Core.ScriptGen;

/// <summary>
/// Orchestrates per-object emitters and wraps the output in a deployment-ready
/// batch. Order:
/// <list type="number">
///   <item>Prologue — Sequences, UserDefinedTypes (alias), Users, Roles
///       (referenced by columns / procedures / role memberships)</item>
///   <item>Tables (with PK / UQ / CK / DF / identity / computed inline)</item>
///   <item>Indexes (CREATE / DROP / delta)</item>
///   <item>Views (CREATE OR ALTER)</item>
///   <item>Functions (CREATE OR ALTER)</item>
///   <item>Procedures (CREATE OR ALTER)</item>
///   <item>Triggers (CREATE OR ALTER)</item>
///   <item>Synonyms (CREATE / DROP — placed after the modules they may alias)</item>
///   <item>FOREIGN KEYS — appended last so referenced tables already exist</item>
///   <item>Permissions — GRANT / REVOKE, gated on
///       <see cref="ComparisonOptions.IgnorePermissions"/> (default ON)</item>
/// </list>
/// </summary>
public sealed class ScriptGenerator
{
    private readonly TableScriptEmitter _tableEmitter = new();
    private readonly IndexScriptEmitter _indexEmitter = new();
    private readonly ForeignKeyScriptEmitter _fkEmitter = new();
    private readonly ViewScriptEmitter _viewEmitter = new();
    private readonly ProcedureScriptEmitter _procEmitter = new();
    private readonly FunctionScriptEmitter _functionEmitter = new();
    private readonly TriggerScriptEmitter _triggerEmitter = new();
    private readonly SequenceScriptEmitter _sequenceEmitter = new();
    private readonly SynonymScriptEmitter _synonymEmitter = new();
    private readonly UserDefinedTypeScriptEmitter _udtEmitter = new();
    private readonly TableTypeUdtScriptEmitter _tableTypeEmitter = new();
    private readonly UserScriptEmitter _userEmitter = new();
    private readonly RoleScriptEmitter _roleEmitter = new();
    private readonly PermissionScriptEmitter _permissionEmitter = new();

    /// <summary>
    /// Generates a complete T-SQL migration script for the given comparison result.
    /// </summary>
    public string Generate(
        ComparisonResult result,
        IEnumerable<DifferencePair>? selection = null,
        ComparisonOptions options = ComparisonOptions.Default)
    {
        ArgumentNullException.ThrowIfNull(result);
        List<DifferencePair> pairs = [.. (selection ?? result.Differences)
            .Where(p => p.Status != DifferenceStatus.Identical)];

        StringBuilder sb = new();
        sb.AppendLine("-- Generated by DbDelta");
        sb.AppendLine("SET XACT_ABORT ON;");
        sb.AppendLine("BEGIN TRANSACTION;");
        sb.AppendLine("GO");

        // 0. Prologue: Sequences + UserDefinedTypes + Users + Roles.
        //    Must come before tables because columns can reference sequences
        //    (DEFAULT NEXT VALUE FOR) and alias UDTs.
        EmitSequences(sb, pairs);
        EmitUserDefinedTypes(sb, pairs);
        EmitTableTypeUdts(sb, pairs);
        EmitUsers(sb, pairs);
        EmitRoles(sb, pairs);

        // 1. Tables (CREATE / DROP / ALTER ADD COLUMN + ALTER ADD CONSTRAINT inline)
        foreach (DifferencePair pair in pairs.Where(p => p.Identity.Kind == "Table"))
        {
            string ddl = _tableEmitter.Emit(pair);
            if (!string.IsNullOrWhiteSpace(ddl))
            {
                sb.AppendLine(ddl);
                sb.AppendLine("GO");
            }
        }

        // 2. Indexes
        //    - New table (OnlyInA): emit CREATE INDEX for every index.
        //    - Existing table (Different): diff against the target side and
        //      emit DROP / CREATE for the delta (M8 polish).
        foreach (DifferencePair pair in pairs.Where(p => p.Identity.Kind == "Table"))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is Table tNew && tNew.Indexes.Count > 0:
                    foreach (TableIndex ix in tNew.Indexes)
                    {
                        sb.AppendLine(_indexEmitter.EmitCreate(tNew.Schema, tNew.Name, ix));
                    }
                    sb.AppendLine("GO");
                    break;

                case DifferenceStatus.Different when pair.SideA is Table tSrc && pair.SideB is Table tTgt:
                    string indexDelta = EmitIndexDelta(tSrc, tTgt);
                    if (indexDelta.Length > 0)
                    {
                        sb.Append(indexDelta);
                        sb.AppendLine("GO");
                    }
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }

        // 3. Views — alphabetical per schema for deterministic output.
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "View")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            string ddl = _viewEmitter.Emit(pair);
            if (!string.IsNullOrWhiteSpace(ddl))
            {
                sb.AppendLine(ddl);
                sb.AppendLine("GO");
            }
        }

        // 4. Functions — alphabetical per schema for deterministic output.
        //    Slots after views so view-of-function dependencies hold.
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "Function")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            string ddl = _functionEmitter.Emit(pair);
            if (!string.IsNullOrWhiteSpace(ddl))
            {
                sb.AppendLine(ddl);
                sb.AppendLine("GO");
            }
        }

        // 5. Procedures — alphabetical per schema for deterministic output.
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "Procedure")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            string ddl = _procEmitter.Emit(pair);
            if (!string.IsNullOrWhiteSpace(ddl))
            {
                sb.AppendLine(ddl);
                sb.AppendLine("GO");
            }
        }

        // 6. Triggers — alphabetical per schema for deterministic output.
        //    Goes after procedures so procs referenced by trigger bodies already exist.
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "Trigger")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            string ddl = _triggerEmitter.Emit(pair);
            if (!string.IsNullOrWhiteSpace(ddl))
            {
                sb.AppendLine(ddl);
                sb.AppendLine("GO");
            }
        }

        // 6.5 Synonyms — placed after the modules they may alias but before
        //     FKs to keep the constraint phase tight at the bottom.
        EmitSynonyms(sb, pairs);

        // 7. Foreign keys — emitted last so referenced tables already exist.
        //    OnlyInA: add every FK. Different: diff against target — drop
        //    removed/changed FKs, add new/changed FKs (M8 polish).
        foreach (DifferencePair pair in pairs.Where(p => p.Identity.Kind == "Table"))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is Table tNew:
                    List<ForeignKey> fksNew = [.. tNew.Constraints.OfType<ForeignKey>()];
                    if (fksNew.Count == 0) { break; }
                    foreach (ForeignKey fk in fksNew)
                    {
                        sb.AppendLine(_fkEmitter.EmitAdd(tNew.Schema, tNew.Name, fk));
                    }
                    sb.AppendLine("GO");
                    break;

                case DifferenceStatus.Different when pair.SideA is Table tSrc && pair.SideB is Table tTgt:
                    string fkDelta = EmitFkDelta(tSrc, tTgt);
                    if (fkDelta.Length > 0)
                    {
                        sb.Append(fkDelta);
                        sb.AppendLine("GO");
                    }
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }

        // 8. Permissions — last, gated on options. Default (Redgate-parity)
        //    skips permissions entirely; consumers can clear the flag to
        //    include GRANT / REVOKE statements.
        if (!options.HasFlag(ComparisonOptions.IgnorePermissions))
        {
            EmitPermissions(sb, pairs);
        }

        sb.AppendLine("COMMIT TRANSACTION;");
        sb.AppendLine("GO");
        return sb.ToString();
    }

    // ── Prologue emitters ───────────────────────────────────────────────────

    private void EmitSequences(StringBuilder sb, IReadOnlyList<DifferencePair> pairs)
    {
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "Sequence")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is Sequence s:
                    sb.AppendLine(_sequenceEmitter.EmitCreate(s));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInB when pair.SideB is Sequence s:
                    sb.AppendLine(_sequenceEmitter.EmitDrop(s));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.Different
                    when pair.SideA is Sequence srcSeq && pair.SideB is Sequence tgtSeq:
                    // SQL Server can ALTER every sequence property except the
                    // base data type. Prefer in-place ALTER so dependent
                    // `DEFAULT NEXT VALUE FOR` defaults survive (parity
                    // scenario 08, 2026-05-25). Fall back to DROP + CREATE
                    // only when the data type itself changed.
                    string? alter = _sequenceEmitter.EmitAlter(srcSeq, tgtSeq);
                    if (alter is null)
                    {
                        sb.AppendLine(_sequenceEmitter.EmitDrop(tgtSeq));
                        sb.AppendLine(_sequenceEmitter.EmitCreate(srcSeq));
                    }
                    else if (alter.Length > 0)
                    {
                        sb.AppendLine(alter);
                    }
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }
    }

    private void EmitUserDefinedTypes(StringBuilder sb, IReadOnlyList<DifferencePair> pairs)
    {
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "UserDefinedType")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is UserDefinedType u:
                    sb.AppendLine(_udtEmitter.EmitCreate(u));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInB when pair.SideB is UserDefinedType u:
                    sb.AppendLine(_udtEmitter.EmitDrop(u));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.Different
                    when pair.SideA is UserDefinedType srcU && pair.SideB is UserDefinedType tgtU:
                    sb.AppendLine(_udtEmitter.EmitDrop(tgtU));
                    sb.AppendLine(_udtEmitter.EmitCreate(srcU));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }
    }

    private void EmitTableTypeUdts(StringBuilder sb, IReadOnlyList<DifferencePair> pairs)
    {
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "TableType")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is TableTypeUdt t:
                    sb.AppendLine(_tableTypeEmitter.EmitCreate(t));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInB when pair.SideB is TableTypeUdt t:
                    sb.AppendLine(_tableTypeEmitter.EmitDrop(t));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.Different
                    when pair.SideA is TableTypeUdt srcT && pair.SideB is TableTypeUdt tgtT:
                    sb.AppendLine(_tableTypeEmitter.EmitDrop(tgtT));
                    sb.AppendLine(_tableTypeEmitter.EmitCreate(srcT));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }
    }

    private void EmitUsers(StringBuilder sb, IReadOnlyList<DifferencePair> pairs)
    {
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "User")
            .OrderBy(p => p.Identity.ObjectName, StringComparer.OrdinalIgnoreCase))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is DatabaseUser u:
                    sb.AppendLine(_userEmitter.EmitCreate(u));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInB when pair.SideB is DatabaseUser u:
                    sb.AppendLine(_userEmitter.EmitDrop(u));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.Different
                    when pair.SideA is DatabaseUser srcU && pair.SideB is DatabaseUser tgtU:
                    if (DefaultSchemaIsOnlyDifference(srcU, tgtU))
                    {
                        sb.AppendLine(_userEmitter.EmitAlterDefaultSchema(srcU));
                        sb.AppendLine("GO");
                    }
                    else
                    {
                        sb.AppendLine(_userEmitter.EmitDrop(tgtU));
                        sb.AppendLine(_userEmitter.EmitCreate(srcU));
                        sb.AppendLine("GO");
                    }
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }
    }

    private static bool DefaultSchemaIsOnlyDifference(DatabaseUser a, DatabaseUser b) =>
        string.Equals(a.TypeCode, b.TypeCode, StringComparison.Ordinal)
        && string.Equals(a.LoginName, b.LoginName, StringComparison.OrdinalIgnoreCase)
        && !string.Equals(a.DefaultSchema, b.DefaultSchema, StringComparison.OrdinalIgnoreCase);

    private void EmitRoles(StringBuilder sb, IReadOnlyList<DifferencePair> pairs)
    {
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "Role")
            .OrderBy(p => p.Identity.ObjectName, StringComparer.OrdinalIgnoreCase))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is DatabaseRole r:
                    sb.AppendLine(_roleEmitter.EmitCreate(r));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInB when pair.SideB is DatabaseRole r:
                    sb.AppendLine(_roleEmitter.EmitDrop(r));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.Different
                    when pair.SideA is DatabaseRole srcR && pair.SideB is DatabaseRole tgtR:
                    EmitRoleDelta(sb, srcR, tgtR);
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }
    }

    private void EmitRoleDelta(StringBuilder sb, DatabaseRole src, DatabaseRole tgt)
    {
        if (!string.Equals(src.OwnerName, tgt.OwnerName, StringComparison.OrdinalIgnoreCase))
        {
            // Owner change requires DROP + CREATE — ALTER AUTHORIZATION exists
            // but ownership swaps are rare enough that DROP + CREATE is the
            // honest path: it surfaces dependent-object failures clearly.
            sb.AppendLine(_roleEmitter.EmitDrop(tgt));
            sb.AppendLine(_roleEmitter.EmitCreate(src));
            sb.AppendLine("GO");
            return;
        }

        HashSet<string> srcMembers = new(src.Members, StringComparer.OrdinalIgnoreCase);
        HashSet<string> tgtMembers = new(tgt.Members, StringComparer.OrdinalIgnoreCase);
        bool wroteAnything = false;
        foreach (string drop in tgtMembers.Except(srcMembers, StringComparer.OrdinalIgnoreCase)
                                          .OrderBy(m => m, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine(_roleEmitter.EmitDropMember(src.Name, drop));
            wroteAnything = true;
        }
        foreach (string add in srcMembers.Except(tgtMembers, StringComparer.OrdinalIgnoreCase)
                                         .OrderBy(m => m, StringComparer.OrdinalIgnoreCase))
        {
            sb.AppendLine(_roleEmitter.EmitAddMember(src.Name, add));
            wroteAnything = true;
        }
        if (wroteAnything)
        {
            sb.AppendLine("GO");
        }
    }

    // ── Epilogue emitters ───────────────────────────────────────────────────

    private void EmitSynonyms(StringBuilder sb, IReadOnlyList<DifferencePair> pairs)
    {
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "Synonym")
            .OrderBy(p => p.Identity.SchemaName)
            .ThenBy(p => p.Identity.ObjectName))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is Synonym s:
                    sb.AppendLine(_synonymEmitter.EmitCreate(s));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInB when pair.SideB is Synonym s:
                    sb.AppendLine(_synonymEmitter.EmitDrop(s));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.Different
                    when pair.SideA is Synonym srcS && pair.SideB is Synonym tgtS:
                    sb.AppendLine(_synonymEmitter.EmitDrop(tgtS));
                    sb.AppendLine(_synonymEmitter.EmitCreate(srcS));
                    sb.AppendLine("GO");
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }
    }

    private void EmitPermissions(StringBuilder sb, IReadOnlyList<DifferencePair> pairs)
    {
        foreach (DifferencePair pair in pairs
            .Where(p => p.Identity.Kind == "Permission")
            .OrderBy(p => p.Identity.ObjectName, StringComparer.Ordinal))
        {
            switch (pair.Status)
            {
                case DifferenceStatus.OnlyInA when pair.SideA is Permission p:
                    sb.AppendLine(_permissionEmitter.EmitGrantOrDeny(p));
                    break;
                case DifferenceStatus.OnlyInB when pair.SideB is Permission p:
                    sb.AppendLine(_permissionEmitter.EmitRevoke(p));
                    break;
                case DifferenceStatus.OnlyInA:
                case DifferenceStatus.OnlyInB:
                case DifferenceStatus.Different:
                case DifferenceStatus.Identical:
                default:
                    break;
            }
        }
    }

    /// <summary>
    /// Builds DROP INDEX / CREATE INDEX statements for the delta between a
    /// pair of versions of the same table. Indexes present only on the
    /// target side are dropped; indexes present only on the source are
    /// created; indexes whose shape differs (key columns / uniqueness /
    /// clustering / filter) are dropped + recreated.
    /// </summary>
    private string EmitIndexDelta(Table src, Table tgt)
    {
        StringBuilder sb = new();
        Dictionary<string, TableIndex> srcByName =
            src.Indexes.ToDictionary(i => i.Name, StringComparer.Ordinal);
        Dictionary<string, TableIndex> tgtByName =
            tgt.Indexes.ToDictionary(i => i.Name, StringComparer.Ordinal);

        // DROPs first so a rename-shaped change frees the slot before CREATE.
        foreach (TableIndex t in tgt.Indexes)
        {
            bool stillThere = srcByName.TryGetValue(t.Name, out TableIndex? s);
            bool shapeChanged = stillThere && !IndexShapeEqual(t, s!);
            if (!stillThere || shapeChanged)
            {
                sb.AppendLine(_indexEmitter.EmitDrop(src.Schema, src.Name, t));
            }
        }
        foreach (TableIndex s in src.Indexes)
        {
            bool existsOnTarget = tgtByName.TryGetValue(s.Name, out TableIndex? t);
            bool shapeChanged = existsOnTarget && !IndexShapeEqual(s, t!);
            if (existsOnTarget && !shapeChanged) { continue; }
            sb.AppendLine(_indexEmitter.EmitCreate(src.Schema, src.Name, s));
        }
        return sb.ToString();
    }

    private static bool IndexShapeEqual(TableIndex a, TableIndex b) =>
        a.IsUnique == b.IsUnique
        && a.IsClustered == b.IsClustered
        && string.Equals(a.FilterExpression, b.FilterExpression, StringComparison.Ordinal)
        && a.KeyColumns.Select(k => $"{k.Name}|{k.IsDescending}")
            .SequenceEqual(b.KeyColumns.Select(k => $"{k.Name}|{k.IsDescending}"), StringComparer.Ordinal)
        && a.IncludedColumns.SequenceEqual(b.IncludedColumns, StringComparer.Ordinal);

    /// <summary>
    /// Builds DROP CONSTRAINT / ADD CONSTRAINT FOREIGN KEY statements for the
    /// FK delta between source and target versions of a table. Mirrors
    /// <see cref="EmitIndexDelta"/>: drops first, then adds; changed FKs are
    /// dropped + re-added.
    /// </summary>
    private string EmitFkDelta(Table src, Table tgt)
    {
        StringBuilder sb = new();
        Dictionary<string, ForeignKey> srcFks =
            src.Constraints.OfType<ForeignKey>().ToDictionary(fk => fk.Name, StringComparer.Ordinal);
        Dictionary<string, ForeignKey> tgtFks =
            tgt.Constraints.OfType<ForeignKey>().ToDictionary(fk => fk.Name, StringComparer.Ordinal);

        foreach (ForeignKey t in tgtFks.Values)
        {
            bool stillThere = srcFks.TryGetValue(t.Name, out ForeignKey? s);
            bool shapeChanged = stillThere && !ForeignKeyShapeEqual(t, s!);
            if (!stillThere || shapeChanged)
            {
                sb.AppendLine($"ALTER TABLE [{src.Schema}].[{src.Name}] DROP CONSTRAINT [{t.Name}];");
            }
        }
        foreach (ForeignKey s in srcFks.Values)
        {
            bool existsOnTarget = tgtFks.TryGetValue(s.Name, out ForeignKey? t);
            bool shapeChanged = existsOnTarget && !ForeignKeyShapeEqual(s, t!);
            if (existsOnTarget && !shapeChanged) { continue; }
            sb.AppendLine(_fkEmitter.EmitAdd(src.Schema, src.Name, s));
        }
        return sb.ToString();
    }

    private static bool ForeignKeyShapeEqual(ForeignKey a, ForeignKey b) =>
        a.Columns.SequenceEqual(b.Columns, StringComparer.Ordinal)
        && string.Equals(a.ReferencedSchema, b.ReferencedSchema, StringComparison.Ordinal)
        && string.Equals(a.ReferencedTable, b.ReferencedTable, StringComparison.Ordinal)
        && a.ReferencedColumns.SequenceEqual(b.ReferencedColumns, StringComparer.Ordinal)
        && a.OnDelete == b.OnDelete
        && a.OnUpdate == b.OnUpdate
        && a.IsDisabled == b.IsDisabled
        && a.IsNotForReplication == b.IsNotForReplication;
}
